# sude: false

# language: node_js

# node_js:
#   - "node"

# script:
#   - npm test
#   - npm run coverage
#   - npm run reboot

# services:
#   -

# env:
#   - NODE_ENV="development";
#   - NODE_ENV="testing";
