sude: false

language: node_js

node_js:
  - "node"

before_script: 
  - psql -c 'create database snacks_test;' -U postgres


script:
  - npm test
  - npm run coverage
  - npm run reboot

services:
  -postgresql 

env:
  - NODE_ENV="testing"
